name: ae2f-workflow
on:
  push:
    branches: [main]
  
jobs:
  test-compiler-majours:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm, windows-11-arm]
        c:  [-DCMAKE_C_COMPILER=gcc, -DCMAKE_C_COMPILER=clang, \"\"]
        conf: [Release, Debug]

        include:
          - os: ubuntu-latest
            bash: bash

          - os: windows-latest
            bash: bash

          - os: macos-latest
            bash: bash
            
          - os: ubuntu-24.04-arm
            bash: bash

          - os: windows-11-arm
            bash: bash

          - c: -DCMAKE_C_COMPILER=gcc
            cc: -DCMAKE_CXX_COMPILER=g++
            
          - c: -DCMAKE_C_COMPILER=clang
            cc: -DCMAKE_CXX_COMPILER=clang++
            
          - c: \"\"
            cc: \"\"

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
        fetch-depth: '1'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
    - name: setupninja-win
      if: matrix.os == 'windows-11-arm'
      uses: seanmiddleditch/gha-setup-ninja@v6

    - name: setupclang-win
      if: matrix.c == '-DCMAKE_C_COMPILER=clang' && matrix.os == 'windows-11-arm' || matrix.os == 'windows-latest'
      uses: egor-tensin/setup-clang@v1

    - name: Setup Vulkan SDK
      # You may pin to the exact commit or the version.
      # uses: humbletim/setup-vulkan-sdk@c25f41106918cde0bf347e6f201277392b3a9e9d
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      
    - name: Test
      run: ${{ matrix.bash }} ./test.sh ${{ matrix.c }} ${{ matrix.cc }} ${{ matrix.conf }}
        
